language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.0
  - nightly

env:
  matrix:
    - DEPENDENCIES=""
    - DEPENDENCIES="--prefer-lowest --prefer-stable"

matrix:
  allow_failures:
    - php: nightly

before_script:
  - composer self-update
  - composer update --prefer-source $DEPENDENCIES

script:
  - ./vendor/bin/phpunit --coverage-clover ./clover.xml
  - ./vendor/bin/phpcs --standard=PSR2 ./src/ ./tests/unit/

after_script:
  - if [ "$TRAVIS_PHP_VERSION" = '7.0' ] ; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover ./clover.xml; fi;
